# Generated by Django 2.0.6 on 2018-06-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('metadata1', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('student_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('raw_data_add', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata1', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata2', models.CharField(blank=True, max_length=50, null=True)),
                ('assignment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='laboratory.Assignment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('title',)},
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('student_name', 'assignment')},
        ),
    ]
